global using System.Collections.Generic;
global using System.ComponentModel;
global using System.IO;
global using System.Linq.Expressions;
global using System.Text;
global using Ater.Web.Core.Utils;
global using Definition.EntityFramework.DBProvider;
global using Definition.Models;
global using Microsoft.EntityFrameworkCore;
global using Project = Definition.Entity.Project;
global using PropertyInfo = Definition.Entity.PropertyInfo;
