global using Mapster;
global using Microsoft.Extensions.Logging;
global using Microsoft.OpenApi;
global using Perigon.MiniDb;
global using Share.Entity;
global using Share.Helper;
global using Share.Models;
global using Share.Utils;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text;
global using PropertyInfo = Share.Models.PropertyInfo;
global using Solution = Share.Entity.Solution;
