global using CodeGenerator;
global using CodeGenerator.Generate;
global using CodeGenerator.Helper;
global using CodeGenerator.Models;
global using Mapster;
global using Microsoft.Extensions.Logging;
global using Share;
global using Share.Entity;
global using Share.Helper;
global using Share.Implement;
global using Share.Models;
global using Share.Services;
global using Share.Utils;
global using System;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Text;
global using System.Text.Json;
global using PropertyInfo = Share.Models.PropertyInfo;
global using Solution = Share.Entity.Solution;
