global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.IO;
global using System.Linq.Expressions;
global using System.Text;
global using Ater.Web.Core.Models;
global using Ater.Web.Core.Utils;
global using CodeGenerator.Helper;
global using Entity;
global using Microsoft.EntityFrameworkCore;
global using Share.EntityFramework.DBProvider;
global using Project = Entity.Project;
global using PropertyInfo = Entity.PropertyInfo;
