global using CodeGenerator.Models;
global using Core.Models;
global using Core.Utils;
global using Entity;
global using Entity.StudioMod;
global using Microsoft.CodeAnalysis;
global using Microsoft.Extensions.Logging;
global using Share.Helper;
global using Share.Models;
global using System.ComponentModel.DataAnnotations;
global using System.Text;
global using System.Text.Json;
global using PropertyInfo = CodeGenerator.Models.PropertyInfo;
global using Solution = Entity.StudioMod.Solution;
