<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>perigon</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <PackageId>Perigon.CLI</PackageId>
    <Version>10.1.7</Version>
    <Description>
			The AI workflow for .NET Web developers, help you generate code and build your project quickly.
		</Description>
    <Authors>NilTor</Authors>
    <Company>Atersoft</Company>
    <Copyright>Atersoft</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/AterDev/Perigon.CLI</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/AterDev/Perigon.CLI</RepositoryUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>1. contain frontend codes when pack module.
		</PackageReleaseNotes>
    <PackageIcon>logo.png</PackageIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>ater;cli;code generate;angular;webapi;asp.net core</PackageTags>
    <Nullable>enable</Nullable>
    <Title>Perigon.CLI</Title>
    <SatelliteResourceLanguages>zh-CN;en-US</SatelliteResourceLanguages>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <None Include="studio.zip" Condition="Exists('studio.zip')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="agent.zip" Condition="Exists('agent.zip')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="ShareDlls.txt" Condition="Exists('ShareDlls.txt')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="nupkg\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\CoreMod\CoreMod.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="logo.png">
      <Pack>True</Pack>
      <PackagePath>
      </PackagePath>
    </None>
  </ItemGroup>
</Project>